name: stale
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 0
          ignore-updates: true
          close-issue-message: |
            This issue has been automatically closed. Please, open a discussion for bug reports and feature requests.
            
            Read more: https://github.com/deployphp/deployer/discussions/3888
          days-before-pr-stale: -1
          days-before-pr-close: -1
          operations-per-run: 1440
